images:
  backend:
    tag: 0be26b91ed50c8b950cb329f8e2035d48901e607
  frontend:
    tag: 0be26b91ed50c8b950cb329f8e2035d48901e607
replicas:
  backend: 1
  frontend: 4
config:
  hibernateDdlAuto: update
  jwtIssuer: user-mgmt-staging
  datasourceUrl: jdbc:postgresql://user-mgmt-postgres:5432/usermgmt_staging
  backendApiUrl: http://user-mgmt-backend:8080
  postgresDatabase: usermgmt_staging
ingress:
  host: staging-user-mgmt-k8s-nt.duckdns.org
autoscaling:
  enabled: false
podDisruptionBudget:
  enabled: false
quota:
  enabled: false
  requestsCpu: "1"
  requestsMemory: 2Gi
  limitsCpu: "2"
  limitsMemory: 4Gi
networkPolicy:
  enabled: false
