images:
  backend:
    tag: 342438b7606a90a48c6d702445d805772156a903
  frontend:
    tag: 342438b7606a90a48c6d702445d805772156a903

replicas:
  backend: 1
  frontend: 1

config:
  hibernateDdlAuto: update
  jwtIssuer: user-mgmt-production
  datasourceUrl: jdbc:postgresql://user-mgmt-postgres:5432/usermgmt_production
  backendApiUrl: http://user-mgmt-backend:8080
  postgresDatabase: usermgmt_production

ingress:
  host: prod-user-mgmt-k8s-nt.duckdns.org
  tls:
    enabled: false

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

quota:
  enabled: true
  requestsCpu: "1"
  requestsMemory: 2Gi
  limitsCpu: "2"
  limitsMemory: 3Gi
  pods: "10"

networkPolicy:
  enabled: true

