images:
  backend:
    tag: 56a9e9773a07472e3affe0d8848f5509ce5fa974
  frontend:
    tag: 56a9e9773a07472e3affe0d8848f5509ce5fa974
replicas:
  backend: 2
  frontend: 2
config:
  hibernateDdlAuto: update
  jwtIssuer: user-mgmt-staging
  datasourceUrl: jdbc:postgresql://user-mgmt-postgres:5432/usermgmt_staging
  backendApiUrl: http://user-mgmt-backend:8080
  postgresDatabase: usermgmt_staging
ingress:
  host: staging.user-mgmt.example.com
quota:
  requestsCpu: "1"
  requestsMemory: 2Gi
  limitsCpu: "2"
  limitsMemory: 4Gi
