images:
  backend:
    tag: 342438b0b787c8d3abd90a40f73aca53499324e4
  frontend:
    tag: 342438b0b787c8d3abd90a40f73aca53499324e4
replicas:
  backend: 1
  frontend: 1
config:
  hibernateDdlAuto: update
  jwtIssuer: user-mgmt-staging
  datasourceUrl: jdbc:postgresql://user-mgmt-postgres:5432/usermgmt_staging
  backendApiUrl: http://user-mgmt-backend:8080
  postgresDatabase: usermgmt_staging
ingress:
  host: staging-user-mgmt-k8s-nt.duckdns.org
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20
  scaleDownStabilizationSeconds: 60
podDisruptionBudget:
  enabled: true
  minAvailable: 1
quota:
  enabled: true
  requestsCpu: "1"
  requestsMemory: 2Gi
  limitsCpu: "2"
  limitsMemory: 4Gi
networkPolicy:
  enabled: true
