apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mgmt-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xxtimmyplaysxx/user-mgmt-ops.git
    targetRevision: main
    path: charts/user-mgmt
    helm:
      releaseName: user-mgmt
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: user-mgmt-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
