apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-mgmt.fullname" . }}-backend
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas.backend }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "user-mgmt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "user-mgmt.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: backend
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: [ALL] }
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.backendPort }}
          envFrom:
            - configMapRef:
                name: {{ include "user-mgmt.fullname" . }}-config
            - secretRef:
                name: {{ include "user-mgmt.secretName" . }}
            {{- if .Values.managedDatabase.enabled }}
            - secretRef:
                name: {{ .Values.managedDatabase.secretName }}
            {{- end }}
          {{- if .Values.managedDatabase.enabled }}
          volumeMounts:
            - name: postgres-ca
              mountPath: /etc/postgres-tls
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          startupProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: http }
            periodSeconds: 5
      {{- if .Values.managedDatabase.enabled }}
      volumes:
        - name: postgres-ca
          secret:
            secretName: {{ .Values.managedDatabase.secretName }}
            items:
              - key: ca.crt
                path: ca.crt
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-mgmt.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "user-mgmt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.service.backendPort }}
      targetPort: http
