apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "user-mgmt.fullname" . }}-postgres-data
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
