{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-mgmt.secretName" . }}
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "secret.postgresPassword is required" .Values.secret.postgresPassword | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ required "secret.postgresPassword is required" .Values.secret.postgresPassword | quote }}
  JWT_SECRET: {{ required "secret.jwtSecret is required" .Values.secret.jwtSecret | quote }}
{{- end }}
